version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ecommerce_dev
      DIRECT_URL: postgres://postgres:postgres@db:5432/ecommerce_dev
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    env_file:
      - ./client/.env
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules

volumes:
  db-data:
